### ISSUE TITLE
Feature Request: New Calendar (MSI, LFL)

### ISSUE THREAD

**Issue by Lukwrt** [ArnoutPullen/LolEsportsCalendar#1]
Hi,

Thank you very much for your work on the calendas, it's pretty awesome.
I wanted to know whether the" Worlds Calendar included the MSI or not.I

If not could you add an "MSI" calendar ?

On a last note, I watch French League "LFL" and I wondered if you could add this calender in addition to the MSI if the MSI is not in Worlds calendar.

If it takes you too much time for you don't worry about all this, thank you again for your work it's very nice.

Regards,
Lucas

**Comment by ArnoutPullen** [comment]
Hello Lucas,

Thank you! MSI is not included in the Worlds Calendar. I have just added the MSI and LFL calendar. Enjoy!

- [MSI](https://calendar.google.com/calendar/u/1?cid=bXV2Y2NxNzA1ZTljdnFocnBtYjB1NHU4c2NAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)
- [LFL](https://calendar.google.com/calendar/u/1?cid=azJrcTh2a2RsdGVxaW5tYWlpNGwxNzRzYzBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

Kind regards,

Arnout
