### ISSUE TITLE
Feature Request: New Calendar

### ISSUE THREAD

**Issue by meakman** [ArnoutPullen/LolEsportsCalendar#2]
Update for current seasons pls

**Comment by ArnoutPullen** [comment]
In which calendar are you missing items?

**Comment by 3li5z3l** [comment]
Can you please update Worlds 2022, Thank you.

**Comment by ArnoutPullen** [comment]
> Can you please update Worlds 2022, Thank you.

Worlds calendar is fixed, thanks for pointing that out!
