### ISSUE TITLE
Feature Request: New Calendar (CBLOL)

### ISSUE THREAD

**Issue by anunciado** [ArnoutPullen/LolEsportsCalendar#3]

**Comment by ArnoutPullen** [comment]
Hi,

You can now use the [CBLOL calender](https://calendar.google.com/calendar/u/1?cid=NGl2azczcWs4MzdubWNuN3ZnaTZsMXZncG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ). Enjoy!
