### ISSUE TITLE
Proposal to Update URL in Readme.md

### ISSUE THREAD

**Issue by KinjiKawaguchi** [ArnoutPullen/LolEsportsCalendar#4]
Hello,

I'm proposing an update to the URL provided in the Readme.md file. The URL in question is: https://calendar.google.com/calendar/u/x?cid=string

Currently, the 'x' in the URL is a placeholder. However, when a user with multiple Google accounts registered on their browser clicks on this link, the calendar might get added to a non-default Google account.

To prevent this from happening, I suggest changing 'x' to '0'. This will ensure that the calendar is added to the user's default Google account regardless of how many accounts they have registered on their browser.

The revised URL would look like this: https://calendar.google.com/calendar/u/0?cid=string

I believe this small change can make a significant difference to users with multiple Google accounts.

Best regards,

[KinjiKawaguchi]

**Comment by ArnoutPullen** [comment]
Hello KinjiKawaguchi,

Thanks for bringing this to my attention, as I wasn't aware of it.
I have just pushed a new commit with the revised URLs.
Hope this helps adding the calendars to your main google account.

Kind Regards,

Arnout
